### ISSUE TITLE
red.pow performance in IE11

### ISSUE THREAD

**Issue by bergr01** [indutny/bn.js#146] opened 2016-05-17 03:45 UTC
Hi,

Using latest version of the library in my application, the red.pow call in Internet Explorer 11 is taking about 30 seconds, while the same call in Firefox/Chrome takes about 5 - is this a known issue with IE11? I didn't see any instructions on how to run the benchmarks or what the results for benchmarks were so can't say for sure...

cheers,
Greg

**Comment by indutny** [comment] 2016-05-20 21:59
Hello!

Unfortunately, I do not have access to any Windows machine, but it is very likely caused by the integer representation in Chakra VM.

I'll try to reach out the Chakra VM team, perhaps they may provide some insights to us.

Thank you!

**Comment by bergr01** [comment] 2016-05-22 21:26
Thanks Fedor, appreciate your assistance on the matter - any suggestions on how I can workaround it (perhaps by using some alternative library or means of computing the end result) would be great, otherwise I guess it's a waiting game for me!

**Comment by indutny** [comment] 2016-05-23 00:25
@bergr01 what kind of use case do you have? I may be able to suggest something if I'll know more details 😉

**Comment by bergr01** [comment] 2016-05-23 07:53
(perhaps the IE11 performance is not as bad as I made it sound in the initial post, but because I'm performing several similar operations as a part of the login process in our application, the slowness becomes more and more obvious)

Essentially we're doing a decryption of RSA-encrypted data - here's the snippet of the test that I whipped up that demonstrates the slowness:

      var data = new BN(base64.decodeToArray('OTZc/IpFG1L6KhtBEjDaKk2tvFGr0G5x9VMApeewV7hNchi3grCTL4T1Nt/2nW+4dBe3YTurNmolMjdAVbO1pmdq4xS9CVLMfdoL8vKYjKwn+d7s4BlXqjenrBREHRxEX8MsEIEAu4CLOxR2o9nTVH5jMwR1bytZDRHGCkEA8k8cj8UU4kykAeQXnQ8ruihm9v4TyZ9NDdSbf1s7euKlzj4U26c7oLSpj6cMHcwxSkkClgiQEBNIq3LbyzrFAGj1cYJdIDUuunplvpqWWH2xg0KdFhMKFHVH3BJTKVK7qlAHyKU1RnEzR4ogoLqKPhA4YD/o4otnajwxgkNFod9ouA=='))
      var objModulus = new BN('19574785637778462136082562659024522829336453149227946442629322350696272968191116874560194158665471167017514526400511330625250395853688901126678522583921108663942451431189570332750692719849505619059264387276570499771979624993327695678724166400013755008573142214277758017337942876293848947414361523211800085847946258976842893840825385641960535262940351558642569708456113314034746877070816618971315247186004383088491615984937888150019045942060824732120558232020173639551372041172791887603161545229139722601152126307703090139032017329546714641319056257113248086172380738586807602804120646928065935473620958712986209013651'.toString(16), 16)
      var objPrivExpo = new BN('118527357583122303294354287631763708176679064112159900717407511576177899347602751825502698963390875507140246698708661972673759841839045815296757460854978001558526676680507110391278716261963147735833978022861168398403658714693260406109124718857115702263384682475027698957030995184541186260671058045499224367922672594354320588562344391689023029947123149612473206028268782707774716602459002934652785428709898552935738309490023958175751946895405102502454997498734196966277777601694533652513471756975490791795591857396758366107679913054905215017736856088554549553801947980998202860346127457304058051771545696084814464565'.toString(16), 16)
      console.log('data length:', data.length, 'objMod length:', objModulus.length, 'objPrivExpo length:', objPrivExpo.length)

      for (var z = 0; z < 10; z++) {
        var tmpStart = Date.now()
        var mR = data.toRed(BN.mont(objModulus))
        var c = mR.redPow(objPrivExpo).fromRed()
        if (c) {
          console.log('Loop: ', z, 'Time taken:', (Date.now() - tmpStart) / 1000, ' seconds')
        }
      }

and here are comparable outputs for Chrome, FF and IE 11:

Chrome:
23 05 2016 17:46:57.499:INFO [Chrome 50.0.2661 (Windows 10 0.0.0)]: Connected on socket /#u_FNDQfMpMUMKB2BAAAA with id 13090367
LOG: 'Starting test at ', Mon May 23 2016 17:46:58 GMT+1000 (AUS Eastern Standard Time)
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'Loop: ', 0, 'Time taken:', 2.054, ' seconds'
LOG: 'Loop: ', 0, 'Time taken:', 2.054, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 2.027, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 2.027, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.898, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.898, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.857, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.857, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.868, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.868, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.86, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.86, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.868, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.868, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.867, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.867, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.892, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.892, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.849, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.849, ' seconds'
  RSA
    IE11 bn slowness
      √ bn seems slow in IE11 (slow: 19.06 secs)

Firefox:
 23 05 2016 17:48:18.034:INFO [Firefox 46.0.0 (Windows 10 0.0.0)]: Connected on socket /#cszpvg7xP-TxQlkXAAAA with id 2325774
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'Loop: ', 0, 'Time taken:', 2.047, ' seconds'
LOG: 'Loop: ', 0, 'Time taken:', 2.047, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 1.618, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 1.618, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.57, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.57, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.58, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.58, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.586, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.586, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.545, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.545, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.622, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.622, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.538, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.538, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.509, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.509, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.578, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.578, ' seconds'
  RSA
    IE11 bn slowness
      √ bn seems slow in IE11 (slow: 16.212 secs) 

IE11:
23 05 2016 17:49:40.128:INFO [launcher]: Starting browser IE
23 05 2016 17:49:41.703:INFO [IE 11.0.0 (Windows 10 0.0.0)]: Connected on socket /#8uRoTtVnZibMJi2nAAAA with id 92755844
LOG: 'Starting test at ', Mon May 23 2016 17:49:42 GMT+1000 (AUS Eastern Standard Time)
LOG: 'Starting test at ', Mon May 23 2016 17:49:42 GMT+1000 (AUS Eastern Standard Time)
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'Loop: ', 0, 'Time taken:', 4.805, ' seconds'
LOG: 'Loop: ', 0, 'Time taken:', 4.805, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 4.753, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 4.753, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 4.767, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 4.767, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 4.748, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 4.748, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 4.804, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 4.804, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 4.96, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 4.96, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 4.881, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 4.881, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 4.735, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 4.735, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 4.754, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 4.754, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 4.719, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 4.719, ' seconds'
  RSA
    IE11 bn slowness
      √ bn seems slow in IE11 (slow: 47.938 secs)

I have been trying to perform these operations in parallel to speed up the login process, but using Promise.all doesn't seem to make much of a difference.

**Comment by indutny** [comment] 2016-05-23 08:04
I'd suggest either using WebWorkers, or using [window.crypto](https://msdn.microsoft.com/en-us/library/dn265046(v=vs.85).aspx) as it appears to be available in IE11.

**Comment by indutny** [comment] 2016-05-23 08:04
At least until it won't be resolved on Chakra level.

**Comment by bergr01** [comment] 2016-05-23 08:13
Thanks Fedor. We're already using window.crypto with IE11 for doing most of the crypto operations however in this particular case we're dealing with data that has been encrypted using algorithm that's not supported in window.crypto (to the best of my knowledge). Using WebWorkers to perform this particular task in a separate thread to the main one certainly has crossed my mind, although in this particular case end-user can't interact with the content after log-in until these time-consuming-in-IE operations can be completed. Anywho, thanks for the suggestions and for reaching out to Chakra team, I'll try finding the lesser of the evils!

**Comment by calvinmetcalf** [comment] 2016-05-23 14:51
RSA is supported by web crypto https://diafygi.github.io/webcrypto-examples/

**Comment by bergr01** [comment] 2016-05-23 23:38
Hi Calvin, if I understand it correctly webcrypto (for encryption/decryption) supports RSAES-PKCS1-v1_5 and RSA-OAEP (e.g. 1.2.840.113549.1.1.7) - however in my case the data was encrypted with plain RSA with PKCS1 padding (1.2.840.113549.1.1.1) and unfortunately converting the data to use newer algorithm is not an option at this stage.

**Comment by indutny** [comment] 2016-05-24 03:18
Is there any way to take a look at generated assembly code in Edge, or get some other compilation artifacts/logs?

**Comment by bergr01** [comment] 2016-05-24 03:38
Performance in Edge for my test snippet actually seems pretty quick (compared to IE11):

24 05 2016 13:36:46.298:INFO [Edge 13.10586.0 (Windows 10 0.0.0)]: Connected on socket /#J5d6PbD7DteKeqMnAAAA with id manual-6003
LOG: 'Starting test at ', Tue May 24 2016 13:36:46 GMT+1000 (AUS Eastern Standard Time)
LOG: 'data length:', 79, 'objMod length:', 95, 'objPrivExpo length:', 95
LOG: 'Loop: ', 0, 'Time taken:', 1.528, ' seconds'
LOG: 'Loop: ', 0, 'Time taken:', 1.528, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 1.616, ' seconds'
LOG: 'Loop: ', 1, 'Time taken:', 1.616, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.506, ' seconds'
LOG: 'Loop: ', 2, 'Time taken:', 1.506, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.496, ' seconds'
LOG: 'Loop: ', 3, 'Time taken:', 1.496, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.538, ' seconds'
LOG: 'Loop: ', 4, 'Time taken:', 1.538, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.56, ' seconds'
LOG: 'Loop: ', 5, 'Time taken:', 1.56, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.503, ' seconds'
LOG: 'Loop: ', 6, 'Time taken:', 1.503, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.513, ' seconds'
LOG: 'Loop: ', 7, 'Time taken:', 1.513, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.465, ' seconds'
LOG: 'Loop: ', 8, 'Time taken:', 1.465, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.54, ' seconds'
LOG: 'Loop: ', 9, 'Time taken:', 1.54, ' seconds'

**Comment by indutny** [comment] 2016-05-24 03:41
Oh well, honestly saying at some point I thought that IE11 is powered by Chakra, and it looks like it isn't.

Sorry @bergr01 , but it is very unlikely that it will be fixed in IE11.

**Comment by bergr01** [comment] 2016-05-24 03:44
No worries, looks like the version that's powering Edge is a fork from the version that's powering IE 8 through to 11 - guess it's all about how much effort M$ is investing in IE11 these days...

**Closed** 2016-06-05 19:42 UTC
Labels: question
