### ISSUE TITLE
-178 = 10 * (-17) + 2, -178 = -10 * 17 + 8

### ISSUE THREAD

**Issue by Yaffle** [indutny/bn.js#47] opened 2015-06-06 06:36 UTC
Your `mod` result is always positive and division is a truncated division, so the quotient `q` and the remainder `r` of `a` divided by `n` do not satisfy `a = nq + r`.
see http://en.wikipedia.org/wiki/Modulo_operation#Remainder_calculation_for_the_modulo_operation

I think, https://github.com/justmoon/node-bignum is correct here.

**Comment by dcousens** [comment] 2015-06-06 09:19
@Yaffle care to add example code?

**Comment by Yaffle** [comment] 2015-06-06 09:57
@dcousens ,

```
      var a = "-178";
      var n = "10";
      var q = new BN(a, 10).div(new BN(n, 10)).toString();
      var r = new BN(a, 10).mod(new BN(n, 10)).toString();
      console.log(`${a} = ${n} * ${q} + ${r}`);
```

**Comment by indutny** [comment] 2015-07-04 18:18
Should be fixed by https://github.com/indutny/bn.js/pull/54 . PTAL.

@dcousens I need to consult with you on this a bit. It is a breaking change, and I wonder if there might be any modules that will need to be updated to support this one. The main difference is that `.mod()` will now return negative number, when the input was negative itself.

There was few places in `elliptic` that needs to be fixed, but it wasn't that complicated (considering that I have pretty big test case).

What are your thoughts? Is it worth fixing, at the price of potentially breaking user code in un-obvious places?

**Comment by dcousens** [comment] 2015-07-07 00:56
This would break a lot of existing ECDSA code where we are relying on this behaviour currently.
Several of my use cases are relying on this behaviour (though, they are using a different BN library right now),  so I'd agree this could have a potentially disastrous effect on users,  at best its absolutely a major version bump IMHO.

@calvinmetcalf thoughts,  I'm pretty sure we're relying on this in crypto-browserify throughout?

**Comment by indutny** [comment] 2015-07-07 01:48
@dcousens I have a pending fix for elliptic library, but this will require major bump on it as well. I guess we can deal with it.

Still would like to hear @calvinmetcalf thoughts on this.

**Comment by jprichardson** [comment] 2015-07-07 01:54
Doesn't it make sense to make the fix for the sake of correctness and predicability and to just bump the major? Maintaining a changelog would help to communicate these sorts of issues for anyone that wants to upgrade major versions.

**Comment by indutny** [comment] 2015-07-07 02:01
@jprichardson the problem is that checking it might be not trivial. But I agree that it should be done.

**Comment by Yaffle** [comment] 2015-07-07 04:02
<table>
<tr>
<th>a</th>
<th>n</th>
<th>mod(master)</th>
<th>umod(fix/gh-47)</th>
<th>Euclidean division</th>
</tr>
<tr>
<th>4</th><th>3</th><td>1</td><td>1</td><td>1</td>
</tr>
<tr>
<th>4</th><th>-3</th><td>1</td><td>1</td><td>1</td>
</tr>
<tr>
<th>-4</th><th>3</th><td>2</td><td>2</td><td>2</td>
</tr>
<tr>
<th>-4</th><th>-3</th><td>1</td><td>-4</td><td>2</td>
</tr>
</table>

**Comment by indutny** [comment] 2015-07-07 04:57
Ok, I think it should throw on negative reduction number in `umod`. Does it sound right?

**Comment by Yaffle** [comment] 2015-07-07 05:05
I think, you might change `umod` to "euclidean division" if you so like non-negative results...

**Comment by indutny** [comment] 2015-07-07 06:17
@Yaffle thanks, fixed.

**Closed** 2015-07-07 23:09 UTC
